class HarnessError(Exception):
    def __init__(self, code, message, owner="PIPELINE", details=None):
        super().__init__(message)
        self.code = code
        self.owner = owner
        self.details = details or {}

CODES = {
    "HASH_MISMATCH", "MISSING_REQUIRED_ARTIFACT", "AMBIGUOUS_PRECEDENCE",
    "INVALID_SCHEMA", "UNKNOWN_VALIDITY", "PROTECTED_CONTENT_SELECTED",
    "SECRET_RISK", "PROVENANCE_GAP", "DUPLICATE_CONFLICT",
    "NONDETERMINISTIC_OUTPUT", "UNSUPPORTED_INPUT", "MR03_IDENTITY_MISMATCH",
    "SOURCE_PATH_ESCAPE", "PROPOSER_SCHEMA_INVALID", "PROPOSAL_SOURCE_REF_INVALID",
    "PROPOSAL_PACKAGE_BINDING_MISMATCH",
}

ERROR_OWNERS = {
    "HASH_MISMATCH": "DISCOVERY",
    "MISSING_REQUIRED_ARTIFACT": "BOUNDED_CONTEXT",
    "AMBIGUOUS_PRECEDENCE": "BOUNDED_CONTEXT",
    "INVALID_SCHEMA": "NORMALIZATION",
    "UNKNOWN_VALIDITY": "BOUNDED_CONTEXT",
    "PROTECTED_CONTENT_SELECTED": "BOUNDED_CONTEXT",
    "SECRET_RISK": "BOUNDED_CONTEXT",
    "PROVENANCE_GAP": "BOUNDED_CONTEXT",
    "DUPLICATE_CONFLICT": "NORMALIZATION",
    "NONDETERMINISTIC_OUTPUT": "VERIFIER",
    "UNSUPPORTED_INPUT": "DISCOVERY",
    "MR03_IDENTITY_MISMATCH": "MR03_ADAPTER",
    "SOURCE_PATH_ESCAPE": "DISCOVERY",
    "PROPOSER_SCHEMA_INVALID": "PROPOSER_STUB",
    "PROPOSAL_SOURCE_REF_INVALID": "VERIFIER",
    "PROPOSAL_PACKAGE_BINDING_MISMATCH": "VERIFIER",
}
